# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a884e9a2808c5ed4b09068035d6d45aa165e62bccd43180e6487635fc97a84eed82f88e68156e47b970597745ec019ff6952f125de627fa59ceb8dc2bb085712

test:
  secret_key_base: c753c3615be445fe0dde7b6364e88fa98d031718c7563a81bd279e046c1044d8142c66912498d67df6dbea2178b2357f513e559bd9f344f59844628080a1c599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
